# -*- coding: utf-8 -*-
"""Ocean Spill/Trash Classifier

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cAVvGTn4Alc1ruLCpmCnSXKGFiMGI4SW
"""

!pip install -U duckduckgo_search

from fastai.vision.all import *

from duckduckgo_search import ddg_images

from fastai.data.all import *

from fastai import *

import time

from time import sleep

from fastai.vision.all import DataBlock, DataLoaders

def search_images(query,max_images = 50):
  return L(ddg_images(query,max_results=max_images)).itemgot('image')

searches = "Ocean Aerial View","dirty ocean aerial view","oil spill ocean aerial view"
path = Path('oceanpics')

for o in searches:
  mkdir(path,exist_ok=True)
  mkdir(path/o,exist_ok = True)
  download_images(path/o,urls = search_images(f'{o} '))
  sleep(1)

failed = verify_images(get_image_files(path))

failed.map(Path.unlink)

dls = DataBlock(
    blocks=(ImageBlock,CategoryBlock),
    get_items = get_image_files,
    splitter = RandomSplitter(valid_pct=.4,seed=12),
    get_y = parent_label,
    item_tfms = Resize(256)
)

dls = dls.dataloaders(path)

learner = vision_learner(dls,resnet34,metrics= error_rate)

learner.fine_tune(10)

learner.path = Path()
learner.export()

path2 = Path('examples')

download_images(path2,urls = L(ddg_images('Daniel Beltra oil spill',max_results=1)).itemgot('image'))
download_images(path2,urls = L(ddg_images('dirty plastic ocean aerial view',max_results=1)).itemgot('image'))
download_images(path2,urls = L(ddg_images('ocean aerial view',max_results=1)).itemgot('image'))
download_images(path2,urls = L(ddg_images('plastic trash in pacific ocean',max_results=1)).itemgot('image'))

fnames = get_image_files(path2)

!pip install gradio
import gradio as gr

labels = learner.dls.vocab
def predict(img):
  img = PILImage.create(img)
  pred,pred_idx,probs = learner.predict(img)
  return {labels[i]: float(probs[i]) for i in range(len(labels))}

gr.Interface(enable_queue= true,title= "Ocean Spill/Trash Detector",fn=predict, inputs=gr.inputs.Image(shape=(256,256)), outputs=gr.outputs.Label(num_top_classes=3),examples=[fnames[0],fnames[1],fnames[2],fnames[3]]).launch(share=True)

fnames

